version: '2.4'

services:
  consul1: &consul-server
    image: consul:1.4.0
    networks:
      - consul
    volumes:
      - ./compose/consul.json:/etc/consul/consul.json
    hostname: consul1
    ports:
      - "38501:8500"
    command:
      agent -config-dir=/etc/consul

  consul2:
    <<: *consul-server
    hostname: consul2
    ports:
      - "38502:8500"

  consul0:
    <<: *consul-server
    hostname: consul0
    ports:
      - "38500:8500"

  metrics:
    image: kamon/grafana_graphite
    networks:
      - consul
    volumes:
      - "./compose/statsd.js:/src/statsd/config.js"
    ports:
      - "8000:80"

  runner:
    image: erlang:21
    networks:
      - consul
    volumes:
      - ${PWD}:${PWD}
    working_dir:
      ${PWD}
    command:
      /usr/local/bin/epmd

networks:
  consul:
